### ISSUE TITLE
Command flags of inkscape 1.1 have changed

### ISSUE THREAD

**Issue by SoptikHa2** [gillescastel/inkscape-figures#18]
Inkscape 1.1 (currently dev edition) has changed it's option `--export-file` to `--export-filename`. This means that current release of `inkscape-figures` doesn't work with Inkscape 1.1 and latter. I don't know which versions do and don't work and when the change occured.

This is fixed in pull request #19.

Tested with `Inkscape 1.1-dev (3a9df5bcce, 2020-03-18)`.

**Comment by gillescastel** [comment]
Thanks a lot! I'll merge your pull request!
