### ISSUE TITLE
explain necessity of latex packages for displaying figures

### ISSUE THREAD

**Issue by Konfekt** [gillescastel/inkscape-figures#2]
Could you expand on the necessity of all the LaTeX packages at

 https://github.com/gillescastel/inkscape-figures/blob/59d7d30290a9b06b93e95355fd4fd1818804f95e/README.md#L24-L27

For example, why is `xifthen` necessary for displaying those figures?

**Comment by gillescastel** [comment]
You're right, the `xifthen` package is not needed for including figures – I removed it from the README. As for the other packages:

- `import` is needed for correct relative import of files.
- `transparent` and `xcolor` are used for transparent and colored text (if not included, text will always be black and opaque)
- `pdfpages` is used for actually including the figures.

Hope that helps. Closing this issue.
