### ISSUE TITLE
Error: undefined variable: b:vimtex

### ISSUE THREAD

**Issue by PeterlitsZo** [gillescastel/inkscape-figures#20]
hi, gillescastel
I try to use your python program on my `wsl`. after I map the `<C-F>`, then I enter the key, the vim show me an `error: undefined variable: b:vimtex`.
I do wrroy about it. Do I lost some step?

by the way, I find your python program use `Popen(['inkscape...`, but I just want to use inkscape in Windows, which should use `/path/to/inkscape.exe` reasonablely. Will it be a good idea to configue it?

---
easy way to deal with it: append `alias inkscape='"/mnt/c/Program Files/Inkscape/inkscape.exe"'`, then it will work well.(but it need command like this: `subprocess.run(['/bin/zsh', '-i', '-c', 'inkscape'])`)

**Comment by gillescastel** [comment]
Are you using [vimtex](https://github.com/lervag/vimtex/)? The vim mappings use vimtex to find the root of your LaTeX document.

For your second question: the scripts as is doesn't support windows, and I'm not sure simply changing that line will make it work, especially the file watching part (although apparently fswatch works on Windows) ... You can try, and if it does, please make a pull request!

**Comment by PeterlitsZo** [comment]
I am doing... To be honest, I forked your project, but it change a lot than you think `0_0`
maybe you will not like my work...
