### ISSUE TITLE
launching Inkscape on macOS

### ISSUE THREAD

**Issue by adir-ux** [gillescastel/inkscape-figures#22]
Ctrl+f doesn't launch Inkscape, although it does create the file in the right position and with the right name (at least for the 1.0beta, the only version which is not dependent on xquartz yet).

Solution:
in 'inkscapefigures' folder in 'main.py' file, inside 'def Inkscape(path):'

subprocess.Popen path is set to "/Applications/Inkscape,set(path)" while this would not work, as its not an executable file (at least that's the reason I found for), and must be changed to:

"/Applications/Inkscape.app/Contents/MacOS/inkscape",str(path)

works like a charm.

thanks a lot for all of your work and sharing. you made me learn ViM from scratch, and build an amazing notes taking machine. your articles and repository are pure gold!

**Comment by gillescastel** [comment]
Not familiar with MacOS, but I think the code as is should work if your path is setup correctly, so I'm hesitant to change it right now. What are your thoughts @pierreglaser?

**Comment by pierreglaser** [comment]
`inkscape` is not so straightfoward to install on `MacOS`, and I may have `symlink`-ed inkscape to some place in my `$PATH` at some point in the process when developing `inkscape-figures` `MacOS` suppport. Apologies if this ended up breaking your setup @adir-ux.


`/Applications/Inkscape.app/Contents/MacOS/inkscape` sounds like a reasonable place for an `Inkscape` executable to be on `MacOS`. But so is `$PATH`. So if we want to support the two, we will need some form of fallback mechanism. Is there any guidelines from the `inkscape` folks on how to launch `inkscape` from the command line in `MacOS`? If not, I would be slightly in favor of supporting @adir-ux 's situation.

**Comment by adir-ux** [comment]
if set to /Applications/Inkscape , would it check the PATH as well?

on Inkscape wiki I found this link to /usr/local/bin
`sudo ln -s /Applications/Inkscape.app/Contents/Resources/bin/inkscape /usr/local/bin`

but running 
`/Applications/Inkscape.app/Contents/Resources/bin/inkscape`
returns "no such file or directory", so I assume it applies only to the older xquartz versions.

someone on StackOverflow suggested the location I pointed.
https://stackoverflow.com/a/60068607

**Comment by gillescastel** [comment]
Thanks for your input! Relevant Inkscape (outdated?) docs: [MacOSX#Inkscape command line](https://wiki.inkscape.org/wiki/index.php/Mac_OS_X#Inkscape_command_line).  A bit confusing to be honest. I think we should probably 

1. check if `inkscape` is in the path (checkout return code of `which inkscape`)
2. check if `/Applications/Inkscape.app/Contents/Resources/bin/inkscape` exists
3. check if `/Applications/Inkscape.app/Contents/MacOS/inkscape` exists,

and depending on that execute the right file. Sounds good?

**Comment by adir-ux** [comment]
sounds great.

**Comment by VonbatenBach** [comment]
Hi, I see the topic of MacOS being called so I'll bump into this conversation. Do you have any idea why Ctrl+S shortcut doesn't return pdf_tex files, but only overwrites svg file? Everything else works just fine :) I use Inkscape 1.0rc1

**Comment by VonbatenBach** [comment]
Debug of watch gives: ValueError: invalid literal for int() with base 10: '0rc1' 
so I guess I know where is the problem, but can't solve it on my own.

**Comment by pierreglaser** [comment]
@VonbatenBach don’t hesitate to open a separate issue if your problem is unrelated to the original report :)

**Comment by gillescastel** [comment]
@VonbatenBach  please open a separate issue. Thanks!

**Comment by gillescastel** [comment]
Moved off-topic conversation to issue #23.
