### ISSUE TITLE
Inkscape Unknown option --export-filename

### ISSUE THREAD

**Issue by Veetikki** [gillescastel/inkscape-figures#25]
Newest version doesn't support `--export-file`, it should be `--export-filename=FILENAME`.

**Comment by SoptikHa2** [comment]
Inkscape version? I encountered this problem while inkscape was in beta and sent merge request which seemed to fix this.

See https://github.com/gillescastel/inkscape-figures/blob/master/inkscapefigures/main.py#L144

**Comment by SoptikHa2** [comment]
Nevermind, I just found out I have the same problem. It looks like inkscape simply changed it's CLI once again. This is the same sort of problem that was in #18 . 
```
Inkscape 1.0 (4035a4fb49, 2020-05-01)
    Pango version: 1.44.7
```

I quickly hacked together a patch, I'll create a pull request. It works for me, but someone should look into it more closely to make sure this won't break with other versions of inkscape.
