### ISSUE TITLE
Do not understand inkscape-figures

### ISSUE THREAD

**Issue by dolefeast** [gillescastel/inkscape-figures#28]
Hi! 
This might be a dumb question but I don't know how to run the inkscape-figures watch on the terminal. I always get the "Command not found". What am I doing wrong? I straight up typed inkscape-figures watch in the terminal inside the folder I'm working in.
What confuses me is that it's the first time I see a python library(I call it like that because I installed it through pip) ran directly from the terminal, as if I were to run $numpy and something would happen.
Thanks in advance.

**Comment by gillescastel** [comment]
Hi @dolefeast, thanks for your question.

You should normally be able to install inkscape-figures and then run it by typing "inkscape-figures" in your terminal. Inkscape-figures is not a library like numpy meant for using in other python files – instead it provides an executable file that can be ran from the terminal.

To further investigate your problem: what OS are you using? How did you install inkscape-figures (please specify the exact command you ran) What was the output when installing?

**Comment by dolefeast** [comment]
Hi. I installed it in Arch (it's like 2 days old so I don't think it's
interfering with other files) using pip3 install inkscape-figures.

**Comment by gillescastel** [comment]
Could you please provide the following? 

* Output when trying to install it? 
* Output of `where inkscape-figures`
* Output of `echo $PATH`

Does any of the following work?

- `pip3 install --user inkscape-figures`
- `python3 -m pip install inkscape-figures`
- `sudo -H pip3 install inkscape-figures`
- `sudo -H python3 -m pip install inkscape-figures`

**Comment by dolefeast** [comment]
`sudo -H pip3 install inkscape-figures` worked. I can run `inkscape-figures` now. 
Thanks a lot!
