### ISSUE TITLE
watch not working on macOS

### ISSUE THREAD

**Issue by roman-dusek** [gillescastel/inkscape-figures#31]
Hey, I can't get "watch" working by saving .svg in Inkscape. Have anyone had the same issue on macOS and got it working? Is there any package I need or change I can make?
I am using macOS Catalina 10.15.7 and Inkscape 1.0.1.

I have actually found a way by adding mapping to vim to call terminal, but I would like to automate it. 
`nnoremap <C-s>:   ! for FILE in ./figures/*.svg; do inkscape -D $FILE  -o .pdf --export-latex; done`

I also tried [this](http://ctan.imsc.res.in/info/svg-inkscape/InkscapePDFLaTeX.pdf) but didnt work at all.

I am quite new into vim, Latex and working with terminal, will be very happy for any advice.

**Comment by UlrichVestuche** [comment]
Hey, Try to 
`Brew install fswatch`
 I got mine working this way.

**Comment by cxdorn** [comment]
@zighj74 thanks this worked for me!
