### ISSUE TITLE
VScode configuration

### ISSUE THREAD

**Issue by sleepymalc** [gillescastel/inkscape-figures#36]
Hi there!
I'm working on the configuration work for almost 1 week, and now I'm glad to say that I somehow manage to let everything happen under macOS + VSCode(without shortcut-manager). I'm wondering that whether it's possible to add a folder for VSCode configuration. I'm quite excited to share all this with everyone, especially at this moment since I know how tough to put all these together with little resources online.
I don't want to put this only in my personal repo, I think here is the best place for this.

**Comment by gillescastel** [comment]
Sure! Feel free to make a pull request.

**Comment by gillescastel** [comment]
I added a directory where you can put your code!

**Comment by sleepymalc** [comment]
Thanks! I make a pr already, thanks for your kindness! I think we can close this issue now.
