### ISSUE TITLE
Clipboard only working when figure changed

### ISSUE THREAD

**Issue by kunzaatko** [gillescastel/inkscape-figures#37]
The latex template of the figure is only copied to clipboard when the figure that is being edited is accually changed. This is due to the clipboard copying being triggerd in the file watcher and that gets triggered only when something changes in the figure.

This can be a problem if you have some figures that you decide to add to the document after removing them earlier without making any changes.

**Comment by gillescastel** [comment]
Confirmed. I'll merge your pull request. Thanks!
