### ISSUE TITLE
Inkscape opening over tiled windows

### ISSUE THREAD

**Issue by vikomen** [gillescastel/inkscape-figures#47]
In the blog, when Castel uses ctr + f an inkscape window opens up on top of both the tilted terminal and zathura. This is seen from here https://castel.dev/a48c6ef9b7407f13e4e0e86b2649333f/including_figure.gif. 

On a closer look, it looks as if desktop environment number is changed.

When I try execute ctr + f however, I get third window in the sense that my screen is split into 3 things - the terminal, zathura, and inkscape.

Does anyone know how I can get the behavior in the gif?

PS: I am using bspwm as I think Castel uses it too?

**Comment by gillescastel** [comment]
Add this to your bspwmrc file:
```
bspc rule -a Inkscape desktop='7'
```
