### ISSUE TITLE
Syntax error on v1.0.4

### ISSUE THREAD

**Issue by miguelraz** [gillescastel/inkscape-figures#7]
Hi Giles!

This is a fantastic package and I 've begun taking my classnotes with your setup.

I've yet to be able to setup the figures because of the following error.

Cheers!

Ubuntu 16.04
```
mrg@mrg-> sudo pip install inkscape-figures 
...

mrg@mrg~> inkscape-figures
Traceback (most recent call last):
  File "/usr/local/bin/inkscape-figures", line 3, in <module>
    from inkscapefigures import cli
  File "/usr/local/lib/python2.7/dist-packages/inkscapefigures/__init__.py", line 1, in <module>
    from .main import cli
  File "/usr/local/lib/python2.7/dist-packages/inkscapefigures/main.py", line 28
    rf"    \incfig{{{name}}}",
                            ^
SyntaxError: invalid syntax
```

**Comment by miguelraz** [comment]
__Fixed it by deleting the `f` in the formatting strings on those 3 or 4 lines.

Feel free to close.__

Edit: This is wrong don't do it.

**Comment by gillescastel** [comment]
Please check your version of python, the script needs version >= 3.7. Simply removing the `f` will make the code run using older versions of Python, but it won't work as expected.

**Comment by miguelraz** [comment]
Ah, thought it would run with Python 3.5. PRing the README.

**Comment by gillescastel** [comment]
Thanks! I've merged your PR.
